<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.0 setup script
 * Date: Fri, 24 Nov 2017 07:17:34 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: vergil.u.washington.edu [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'vergil.u.washington.edu';
$cfg['Servers'][$i]['port'] = 8800;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'HuskySailingSiteAdmin!';

/* End of servers configuration */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>